Repository mitxpro-dev/learnjs, pull requests merged in 2023-07, with the labels that each got.

#13 adds a hero image and breaks out styling, removes VStack
  src/app/page.tsx
Labels: enhancement

#18 Feat/Add nav and layout max width
  src/app/layout.tsx
  src/components/Navigation.tsx
Labels: enhancement, merge for me

#14 Issue-17/Docs/Add project details to readme
  README.md
Labels: documentation, merge for me

#16 Issue-15/Feat/Dynamic routes for single challenges
  src/app/challenges/[challenge]/page.tsx
Labels: enhancement, merge for me

#19 Feat/Add about page content
  src/app/about/page.tsx
Labels: enhancement, merge for me

#24 feat: Pivot to SWC, Vite, React, TS
  .eslintrc.cjs
  .github/workflows/build-check.yml
  .github/workflows/build-deploy.yml
  .gitignore
  index.html
  next.config.js
  package-lock.json
  package.json
  public/next.svg
  public/vercel.svg
  src/App.tsx
  src/RootLayout.tsx
  src/app/challenges/[challenge]/page.tsx
  src/app/favicon.ico
  src/app/layout.tsx
  src/app/providers.tsx
  src/components/Footer.tsx
  src/components/NavLink.tsx
  src/components/Navigation.tsx
  src/main.tsx
  src/pages/about.tsx
  src/pages/challenges/challenge.tsx
  src/pages/challenges/index.tsx
  src/pages/index.tsx
  tsconfig.json
  tsconfig.node.json
  tsconfig.tsbuildinfo
  vite.config.ts
Labels: enhancement

#27 bug: fix vite base URL
  vite.config.ts
Labels: bug

#28 Feat: Markdown
  package-lock.json
  package.json
  src/components/ChallengeBody.tsx
  src/components/MarkdownComponents/Blockquote.tsx
  src/components/MarkdownComponents/Code/WindowButton.tsx
  src/components/MarkdownComponents/Code/index.tsx
  src/components/MarkdownComponents/Hr.tsx
  src/components/MarkdownComponents/Table.tsx
  src/components/MarkdownComponents/index.tsx
  src/components/Navigation.tsx
  src/pages/challenges/challenge.tsx
Labels: enhancement

#35 Docs/issue-34/update readme and add license
  LICENSE
  README.md
Labels: documentation, merge for me

#44 Issue-43/Fix/Router
  src/App.tsx
Labels: merge for me, fix
